@host = https://http-quiz.maharrer.now.sh

GET {{host}}/ HTTP/1.1

###

GET {{host}}/?username=Harald HTTP/1.1

###

POST {{host}}/ HTTP/1.1

Harald

###

POST https://http-quiz.maharrer.now.sh/ HTTP/1.1
Content-Type: text/plain

Harald

###

GET {{host}}/next-steps HTTP/1.1

###

OPTIONS {{host}}/next-steps HTTP/1.1

###

DELETE {{host}}/next-steps HTTP/1.1

###

DELETE {{host}}/next-steps HTTP/1.1
Authorization: Bearer 8a5ed8b0b3ed4d698e52ee7d14ed405d

###

PUT {{host}}/your-steps HTTP/1.1

###

PUT {{host}}/your-steps HTTP/1.1

SOMETHING

###

POST {{host}}/rating/stars/5 HTTP/1.1

###
# ADDITIONAL
###


GET {{host}}/all-ratings HTTP/1.1

###

DELETE {{host}}/all-ratings HTTP/1.1

###

DELETE {{host}}/all-sessions HTTP/1.1
